import React, { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import Navigation from "@/components/Navigation";
import PremiumReportV2 from "@/components/report-v2/PremiumReportV2";
import api, { ASSET_BASE } from "@/lib/api";
import {
  Loader2, ArrowRight, Download, ShieldCheck, Crosshair, HeartHandshake, FileText, Sparkles,
} from "lucide-react";

const LIME = "#ccff00";

const FEATURES = [
  { icon: ShieldCheck, label: "AI-verified evidence frames" },
  { icon: Crosshair, label: "Optical player tracking" },
  { icon: HeartHandshake, label: "Parent package & home drills" },
  { icon: FileText, label: "Printable premium PDF" },
];

export default function SampleReportPage() {
  const [report, setReport] = useState(null);
  const [loading, setLoading] = useState(true);
  const [ctaBar, setCtaBar] = useState(false);

  useEffect(() => {
    document.title = "Sample Scout Report — ScoutMePlay";
    window.scrollTo(0, 0);
    api.get("/sample/report")
      .then((r) => setReport(r.data))
      .catch(() => {})
      .finally(() => setLoading(false));
    return () => { document.title = "ScoutMePlay"; };
  }, []);

  useEffect(() => {
    const onScroll = () => setCtaBar(window.scrollY > 700);
    onScroll();
    window.addEventListener("scroll", onScroll, { passive: true });
    return () => window.removeEventListener("scroll", onScroll);
  }, []);

  const overall = report?.full_report?.scores?.overall_development;
  const pd = report?.player_details || {};

  return (
    <div className="min-h-screen bg-[#F2EDE2]" data-testid="sample-report-page">
      <Navigation />

      {/* ===== HERO — dark sales band ===== */}
      <section className="bg-ink text-white relative overflow-hidden">
        <div
          aria-hidden
          className="absolute inset-0 opacity-[0.07] pointer-events-none"
          style={{ backgroundImage: `radial-gradient(ellipse 60% 80% at 85% 20%, ${LIME}, transparent 60%)` }}
        />
        <div className="max-w-7xl mx-auto px-4 sm:px-6 md:px-10 pt-14 md:pt-20 pb-12 md:pb-16 relative">
          <div className="grid lg:grid-cols-[1.4fr_1fr] gap-10 items-center">
            <div>
              <p className="flex items-center gap-2 text-[11px] uppercase tracking-[0.24em] font-bold mb-5" style={{ color: LIME }}>
                <Sparkles className="w-3.5 h-3.5" /> Live sample · Real AI analysis
              </p>
              <h1 className="font-barlow font-black uppercase leading-[0.95] text-4xl sm:text-5xl lg:text-6xl">
                This is what<br />you get<span style={{ color: LIME }}>.</span>
              </h1>
              <p className="mt-5 text-white/65 text-base max-w-xl leading-relaxed">
                A genuine premium scout report generated by our AI from one uploaded video —
                anonymized for privacy. Every card below is exactly what lands in your inbox.
              </p>
              <div className="mt-7 flex flex-wrap items-center gap-3">
                <Link
                  to="/signup"
                  data-testid="sample-hero-cta"
                  className="group flex items-center gap-2 font-barlow font-black uppercase tracking-widest text-sm px-7 py-3.5 rounded-full transition-transform hover:scale-[1.03]"
                  style={{ background: LIME, color: "#0A1F0F" }}
                >
                  Get your own report
                  <ArrowRight className="w-4 h-4 group-hover:translate-x-0.5 transition-transform" />
                </Link>
                <a
                  href={`${ASSET_BASE}/api/sample/scoutmeplay-report.pdf`}
                  target="_blank"
                  rel="noreferrer"
                  data-testid="sample-pdf-link"
                  className="flex items-center gap-2 border border-white/25 hover:border-white/60 text-white/85 hover:text-white font-bold uppercase tracking-widest text-xs px-6 py-3.5 rounded-full transition-colors"
                >
                  <Download className="w-4 h-4" /> Sample PDF
                </a>
              </div>
              <div className="mt-8 flex flex-wrap gap-2.5">
                {FEATURES.map(({ icon: Icon, label }) => (
                  <span key={label} className="flex items-center gap-1.5 bg-white/5 border border-white/10 text-white/70 text-[11px] font-bold uppercase tracking-wider px-3 py-1.5 rounded-full">
                    <Icon className="w-3.5 h-3.5" style={{ color: LIME }} /> {label}
                  </span>
                ))}
              </div>
            </div>

            {/* Score teaser card */}
            {overall != null && (
              <div className="hidden lg:flex justify-end">
                <div className="bg-white/[0.06] border border-white/10 rounded-2xl p-8 text-center backdrop-blur-sm" data-testid="sample-hero-score">
                  <p className="text-[10px] uppercase tracking-[0.28em] font-bold text-white/50">Overall score</p>
                  <p className="font-barlow font-black text-7xl mt-2" style={{ color: LIME }}>{Number(overall).toFixed(1)}</p>
                  <p className="text-xs text-white/55 mt-2 uppercase tracking-widest font-bold">
                    {pd.player_name} · {pd.position || "Player"}{pd.age ? ` · U${pd.age + 1}` : ""}
                  </p>
                  <p className="mt-4 text-[11px] text-white/40 leading-relaxed max-w-[220px]">
                    Scored across technique, tactics, physique and mentality — calibrated to age group.
                  </p>
                </div>
              </div>
            )}
          </div>
        </div>
        {/* Demo ribbon */}
        <div className="py-2.5 text-center text-[11px] font-black uppercase tracking-[0.22em]" style={{ background: LIME, color: "#0A1F0F" }} data-testid="sample-demo-ribbon">
          Anonymized demo — real report, real footage, real AI verdicts
        </div>
      </section>

      {/* ===== THE REPORT ===== */}
      <div className="pt-10 md:pt-12 px-4 md:px-8 pb-24">
        {loading ? (
          <div className="py-32 text-center">
            <Loader2 className="w-8 h-8 animate-spin text-forest mx-auto" />
            <p className="mt-4 text-[#12402A]/60 uppercase tracking-widest text-sm font-bold">Loading sample report...</p>
          </div>
        ) : report ? (
          <PremiumReportV2 report={report} assetBase={ASSET_BASE} />
        ) : (
          <div className="py-32 text-center text-[#12402A]/60">
            <p className="font-bold uppercase tracking-widest text-sm">Sample report is being prepared — check back shortly.</p>
          </div>
        )}

        {/* Bottom conversion block */}
        {report && (
          <div className="max-w-[1440px] mx-auto mt-12">
            <div className="bg-ink rounded-2xl px-8 py-12 md:px-14 text-center relative overflow-hidden" data-testid="sample-bottom-cta">
              <div aria-hidden className="absolute inset-0 opacity-[0.08] pointer-events-none" style={{ backgroundImage: `radial-gradient(ellipse 50% 90% at 50% 0%, ${LIME}, transparent 65%)` }} />
              <h2 className="font-barlow font-black uppercase text-white text-lg md:text-lg tracking-wide relative">
                Your player deserves the same report
              </h2>
              <p className="text-white/60 text-sm mt-3 max-w-lg mx-auto relative">
                Upload one video, mark your player with a tap, and get a free AI preview — no card required to start.
              </p>
              <Link
                to="/signup"
                data-testid="sample-bottom-cta-btn"
                className="relative inline-flex items-center gap-2 mt-7 font-barlow font-black uppercase tracking-widest text-sm px-8 py-4 rounded-full transition-transform hover:scale-[1.03]"
                style={{ background: LIME, color: "#0A1F0F" }}
              >
                Start free preview <ArrowRight className="w-4 h-4" />
              </Link>
            </div>
          </div>
        )}
      </div>

      {/* ===== Sticky CTA bar (appears on scroll) ===== */}
      <div
        data-testid="sample-sticky-cta"
        className={`fixed bottom-0 left-0 right-0 z-40 transition-all duration-300 ${ctaBar ? "translate-y-0 opacity-100" : "translate-y-full opacity-0 pointer-events-none"}`}
      >
        <div className="bg-ink/95 backdrop-blur-xl border-t border-white/10">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 md:px-10 py-3 flex items-center justify-between gap-4">
            <p className="text-white/80 text-xs sm:text-sm font-bold uppercase tracking-wider hidden sm:block">
              Want this for your player? <span className="text-white/45 normal-case font-medium tracking-normal">Free preview · no card needed</span>
            </p>
            <Link
              to="/signup"
              data-testid="sample-sticky-cta-btn"
              className="flex items-center gap-2 font-barlow font-black uppercase tracking-widest text-xs sm:text-sm px-6 py-2.5 rounded-full ml-auto transition-transform hover:scale-[1.03]"
              style={{ background: LIME, color: "#0A1F0F" }}
            >
              Get your report <ArrowRight className="w-4 h-4" />
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
}
